// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaif2bwJYw5RtTZjRFoddCunshVY3-_z8',
    appId: '1:858786542446:web:e989c96065a6e2ddb9077f',
    messagingSenderId: '858786542446',
    projectId: 'speedcharge-412914',
    authDomain: 'speedcharge-412914.firebaseapp.com',
    storageBucket: 'speedcharge-412914.appspot.com',
    measurementId: 'G-5VESY79EKN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOHG9wWomUlPVKcwzrwHWzrwFuM0H46Tk',
    appId: '1:858786542446:android:69380aa047e2ba59b9077f',
    messagingSenderId: '858786542446',
    projectId: 'speedcharge-412914',
    storageBucket: 'speedcharge-412914.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4Z3FRpYP3US2kfu0KktZLKKsLcFRXeKE',
    appId: '1:858786542446:ios:b4efdbede47d1d56b9077f',
    messagingSenderId: '858786542446',
    projectId: 'speedcharge-412914',
    storageBucket: 'speedcharge-412914.appspot.com',
    iosBundleId: 'com.example.flSpeedcharge',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4Z3FRpYP3US2kfu0KktZLKKsLcFRXeKE',
    appId: '1:858786542446:ios:b4efdbede47d1d56b9077f',
    messagingSenderId: '858786542446',
    projectId: 'speedcharge-412914',
    storageBucket: 'speedcharge-412914.appspot.com',
    iosBundleId: 'com.example.flSpeedcharge',
  );
}
